version: 1.0.{build}

image: Visual Studio 2017

build:
  verbosity: minimal

environment:
  matrix:
    - build_name: mingw73_32_qt5_12_4
      QTPATH: C:\Qt\5.12.4\mingw73_32
      MINGW32: C:\Qt\Tools\mingw730_32
#    - build_name: msvc2017_64
#      QTPATH: C:\Qt\5.11.2\msvc2017_64
#      MINGW32: C:\Qt\Tools\mingw530_32

install:
  - cd %APPVEYOR_BUILD_FOLDER%
  - git submodule update --init --recursive
  - set PATH=%PATH%;%QTPATH%\bin;%MINGW32%\bin

build_script:
  - mkdir build
  - cd build
  - qmake ..\PineapplePictures.pro
  - mingw32-make
  - cd release
  - del /a /f /q "*.o"  "*.cpp" "*.h"
  - windeployqt --no-quick-import  --release .\PineapplePictures.exe

artifacts:
  - path: build\release
